#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
     path: /{_locale}
     controller: App\Controller\DefaultController::homepage
     defaults:
          _locale: 'en'
     requirements:
          _locale: 'en|fr'
     
add_product:
     path: /{_locale}/add/product
     controller: App\Controller\ProductController::addProduct
     requirements:
          _locale: 'en|fr'

list_product:
     path: /{_locale}/list/product
     controller: App\Controller\ProductController::listProduct
     requirements:
          _locale: 'en|fr'
      
register_user:
     path: /{_locale}/register/user
     controller: App\Controller\UserController::registerUser    
     requirements:
          _locale: 'en|fr' 
     
user_activate:
     path: /{_locale}/user/activate/{token}
     controller: App\Controller\UserController::activateUser
     requirements:
          _locale: 'en|fr'
          token: '[a-z0-9-]+' 

username_available:
    path: /username/available
    controller: App\Controller\UserController::usernameAvailable
    methods: ['POST']      
    
login:
    path: /{_locale}/login
    controller: App\Controller\UserController::login
    defaults:
      _locale: 'en'   
    requirements:
       _locale: 'en|fr' 
 
logout:
    path: /logout

 
    
    
    
       
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    